<div class="page-content">
	<!-- BEGIN PAGE HEADER-->
	<h3 class="page-title">
	<?php echo mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?>
	</h3>
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<i class="fa fa-home"></i>
				<a href="<?php echo $this->url->getBaseUri().'admin'; ?>">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="#"><?php echo mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?></a>
			</li>
		</ul>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
			<?php $this->flash->output() ?>
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box grey-cascade">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-globe"></i>Managed Table
					</div>
				</div>
				<div class="portlet-body">
					<div class="table-toolbar">
						<div class="row">
							<div class="col-md-6">
								<div class="btn-group">
									<button link_to="<?php echo $this->url->get('admin/$plural$/new/'); ?>" class="btn green">
									Add New <i class="fa fa-plus"></i>
									</button>
								</div>
							</div>
							<div class="col-md-6">
								<div class="btn-group pull-right">
									<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
									</button>
									<ul class="dropdown-menu pull-right">
										<li>
											<a href="javascript:;">
											Print </a>
										</li>
										<li>
											<a href="javascript:;">
											Save as PDF </a>
										</li>
										<li>
											<a href="javascript:;">
											Export to Excel </a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<table class="table table-striped table-bordered table-hover" id="table_$plural$">
						<thead>
							<tr>
								$headerColumns$
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						
						<?php foreach ($$plural$ as $singularVar$) { ?>
							<tr class="odd gradeX">
								$rowColumns$            
								<td>
									<?php echo $this->tag->linkTo(array("admin/$plural$/view/" . $singularVar$->$pk$, '<span class="glyphicon glyphicon-search"></span>')); ?> | 
									<?php echo $this->tag->linkTo(array("admin/$plural$/edit/" . $singularVar$->$pk$, '<span class="glyphicon glyphicon-edit"></span>')); ?> | 
									<?php echo $this->tag->linkTo(array("admin/$plural$/delete/" . $singularVar$->$pk$, '<span class="glyphicon glyphicon-trash"></span>', "confirm" => "true")); ?>
								</td>
							</tr>
						<?php } ?>
					
						</tbody>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
<script type="text/javascript">
    jQuery(document).ready(function() { 
        var table = $('#table_$plural$');
        // begin: third table
        table.dataTable({

            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "Show _MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },
            
            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js). 
            // So when dropdowns used the scrollable div should be removed. 
            //"dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.
            
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 5,
            "language": {
                "lengthMenu": " _MENU_ records"
            },
            "columnDefs": [{  // set default column settings
                'orderable': false,
                'targets': []
            }, {
                "searchable": false,
                "targets": [0]
            }],
            "order": [
                [1, "asc"]
            ] // set first column as a default sort by asc
        });

        var tableWrapper = jQuery('#table_$plural$_wrapper');
        tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown
    });
</script>