<div class="page-content">
	<!-- BEGIN PAGE HEADER-->
	<h3 class="page-title">
	<?php echo 'Add New '.mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?>
	</h3>
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<i class="fa fa-home"></i>
				<a href="<?php echo $this->url->getBaseUri().'admin'; ?>">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="<?php echo $this->url->get('admin/$plural$/'); ?>"><?php echo mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?></a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="#">Add New <?php echo mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?></a>
			</li>
		</ul>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
			<?php $this->flash->output() ?>
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box grey-cascade">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-globe"></i>Managed Table
					</div>
				</div>
				<div class="portlet-body form">
				<?php echo $this->tag->form(array("", 'class' => 'form-horizontal')) ?>
				<div class="form-body">
					$captureFields$
				</div>
				<div class="form-actions">
					<div class="row">
						<div class="col-md-offset-3 col-md-9">
							<button class="btn green" type="submit">Save</button>
							<button link_to="<?php echo $this->url->get('admin/$plural$/'); ?>" class="btn default" type="button">Cancel</button>
						</div>
					</div>
				</div>
				
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
