<div class="page-content">
	<!-- BEGIN PAGE HEADER-->
	<h3 class="page-title">
	<?php echo 'View '.mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?>
	</h3>
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<i class="fa fa-home"></i>
				<a href="<?php echo $this->url->getBaseUri().'admin'; ?>">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="<?php echo $this->url->get('admin/$plural$/'); ?>"><?php echo mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?></a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="#">View <?php echo mb_convert_case('$plural$', MB_CASE_TITLE, "UTF-8"); ?></a>
			</li>
		</ul>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
			<?php $this->flash->output() ?>
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box grey-cascade">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-globe"></i>Managed Table
					</div>
				</div>
				<div class="portlet-body">
					<div id="table_slides_wrapper" class="dataTables_wrapper no-footer">
                        <div class="table-scrollable">
                            <table class="table table-striped table-bordered table-hover">
                                <tbody>
                                    $captureFields$
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button link_to="<?php echo $this->url->get('admin/$plural$/'); ?>" class="btn default" type="button">Back</button>
                        </div>
                    </div>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
